### PR TITLE
Please Approve

### PR DESCRIPTION
**Pull request by Eastina**
the pull request

### CODE REVIEW

**Review by edb-cliveaw — APPROVED** [review]

**Comment by Eastina** [comment]
Message Classification: Restricted
Hi guys,

My colleague has approved it.

**Comment by LoneRifle** [comment]
@Eastina - to complete this, you are to tap or click the green button on the link https://github.com/isomerpages/edb-ostIn/pull/1 :
image


Under _no_ circumstances will the Isomer team approve or merge pull requests. The content in an Isomer site is the sole responsibility of the user's agency, and the agency should not give this responsibility away to anyone else, much less the Isomer team.

**Comment by Eastina** [comment]
Message Classification: Restricted
I don't understand what im supposed to do there. Cant find that green button.

**Comment by Eastina** [comment]
hi guys i think its merged and done. anything else to follow up on?

**Comment by Eastina** [comment]
Hi guys, thanks for launching the website for us. Can i check, everytime we update the site with articles/ info, will the updates be reflected on the website live, or must there be a certain process to get it updated?

**Pull request merged**
